export const images=[
    {
        id:1,
        root:'../../assets/image/board/blue2.thumbnail.jpg',
        even:'../../assets/image/board/blue21.jpg',
        odd:'../../assets/image/board/blue22.jpg',
        border:'#5d768a'
    },
    {
        id:2,
        root:'../../assets/image/board/blue3.thumbnail.jpg',
        even:'../../assets/image/board/blue31.jpg',
        odd:'../../assets/image/board/blue32.jpg',
        border:'#406fa5'
    },
    {
        id:3,
        root:'../../assets/image/board/blue-marble.thumbnail.jpg',
        even:'../../assets/image/board/blue-marble1.jpg',
        odd:'../../assets/image/board/blue-marble2.jpg',
        border:'#93a1ae'
    },
    {
        id:4,
        root:'../../assets/image/board/canvas2.thumbnail.jpg',
        even:'../../assets/image/board/canvas1.jpg',
        odd:'../../assets/image/board/canvas2.jpg',
        border:'#7586a2'
    },
    {
        id:5,
        root:'../../assets/image/board/green-plastic.thumbnail.png',
        even:'../../assets/image/board/green-plastic1.png',
        odd:'../../assets/image/board/green-plastic2.png',
        border:'#59935d'
    },
    {
        id:6,
        root:'../../assets/image/board/grey.thumbnail.jpg',
        even:'../../assets/image/board/grey1.jpg',
        odd:'../../assets/image/board/grey2.jpg',
        border:'#878787'
    },
    {
        id:7,
        root:'../../assets/image/board/leather.thumbnail.jpg',
        even:'../../assets/image/board/leather-10241.jpg',
        odd:'../../assets/image/board/leather-10242.jpg',
        border:'#bc8712'
    },
    {
        id:8,
        root:'../../assets/image/board/maple.thumbnail.jpg',
        even:'../../assets/image/board/maple1.jpg',
        odd:'../../assets/image/board/maple1-2.jpg',
        border:'#ae6835'
    },
    {
        id:9,
        root:'../../assets/image/board/maple2.thumbnail.jpg',
        even:'../../assets/image/board/maple2-1.jpg',
        odd:'../../assets/image/board/maple2-2.jpg',
        border:'#9b6348'
    },
    {
        id:10,
        root:'../../assets/image/board/marble.thumbnail.jpg',
        even:'../../assets/image/board/marble1.jpg',
        odd:'../../assets/image/board/marble1-2.jpg',
        border:'#5f775f'
    },
    {
        id:11,
        root:'../../assets/image/board/metal.thumbnail.jpg',
        even:'../../assets/image/board/metal1.jpg',
        odd:'../../assets/image/board/metal1-2.jpg',
        border:'#6f6f6f'
    },
    {
        id:12,
        root:'../../assets/image/board/newspaper.thumbnail.png',
        even:'../../assets/image/board/newspaper1.png',
        odd:'../../assets/image/board/newspaper2.png',
        border:'#c8c8c8'
    },
    {
        id:13,
        root:'../../assets/image/board/pink-pyramid.thumbnail.png',
        even:'../../assets/image/board/pink-pyramid1.png',
        odd:'../../assets/image/board/pink-pyramid2.png',
        border:'#f27373'
    },
    // {
    //     id:14,
    //     root:'../../assets/image/board/purple.thumbnail.png',
    //     even:'../../assets/image/board/purple1.png',
    //     odd:'../../assets/image/board/purple2.png'
    // },
    {
        id:15,
        root:'../../assets/image/board/purple-diag.thumbnail.png',
        even:'../../assets/image/board/purple-diag1.png',
        odd:'../../assets/image/board/purple-diag2.png',
        border:'#997db5'
    },
    {
        id:16,
        root:'../../assets/image/board/wood.thumbnail.jpg',
        even:'../../assets/image/board/wood1.jpg',
        odd:'../../assets/image/board/wood1-2.jpg',
        border:'#874d20'
    },
    {
        id:17,
        root:'../../assets/image/board/wood2.thumbnail.jpg',
        even:'../../assets/image/board/wood2-1.jpg',
        odd:'../../assets/image/board/wood2-2.jpg',
        border:'#755d2f'
    },
    {
        id:18,
        root:'../../assets/image/board/wood3.thumbnail.jpg',
        even:'../../assets/image/board/wood3-1.jpg',
        odd:'../../assets/image/board/wood3-2.jpg',
        border:'#815f39'
    },
    {
        id:19,
        root:'../../assets/image/board/wood4.thumbnail.jpg',
        even:'../../assets/image/board/wood41.jpg',
        odd:'../../assets/image/board/wood42.jpg',
        border:'#885d33'
    },
    {
        id:20,
        root:'../../assets/image/board/olive.thumbnail.jpg',
        even:'../../assets/image/board/olive1.jpg',
        odd:'../../assets/image/board/olive2.jpg',
        border:'#c8c8c8'
    },
    {
        id:21,
        root:'../../assets/image/board/horsey.thumbnail.jpg',
        even:'../../assets/image/board/horsey1.jpg',
        odd:'../../assets/image/board/horsey2.jpg',
        border:'#936a4b'
    },
]

export const boardPieces=[
    {id:1,name:'Alpha',url:'/alpha/'},
    {id:2,name:'California',url:'/california/'},
    {id:3,name:'Cardinal',url:'/cardinal/'},
    {id:4,name:'Cburnett',url:'/cburnett/'},
    {id:5,name:'Chess7',url:'/chess7/'},
    {id:6,name:'ChessNut',url:'/chessnut/'},
    {id:7,name:'Companion',url:'/companion/'},

    {id:8,name:'Dubrovny',url:'/dubrovny/'},
    {id:9,name:'fantasy',url:'/fantasy/'},
    {id:10,name:'fresca',url:'/fresca/'},
    {id:11,name:'gioco',url:'/gioco/'},
    {id:12,name:'governor',url:'/governor/'},
    {id:13,name:'horsey',url:'/horsey/'},
    {id:14,name:'icpieces',url:'/icpieces/'},

    {id:15,name:'kosal',url:'/kosal/'},
    {id:16,name:'leipzig',url:'/leipzig/'},
    {id:17,name:'letter',url:'/letter/'},
    {id:18,name:'libra',url:'/libra/'},
    {id:19,name:'maestro',url:'/maestro/'},
    {id:20,name:'merida',url:'/merida/'},
    {id:21,name:'pirouetti',url:'/pirouetti/'},

    {id:22,name:'pixel',url:'/pixel/'},
    {id:23,name:'reillycraig',url:'/reillycraig/'},
    {id:24,name:'riohacha',url:'/riohacha/'},
    {id:25,name:'shapes',url:'/shapes/'},
    {id:26,name:'spatial',url:'/spatial/'},
    {id:27,name:'staunty',url:'/staunty/'},
    {id:28,name:'tatiana',url:'/tatiana/'},

] 